### ISSUE TITLE
0x76 Address issue with I2c connection in Rpi3

### ISSUE THREAD

**Issue by vasee007** [adafruit/Adafruit_CircuitPython_BMP280#16]
Hi,
    I'm using a BMP280 sensor module with raspberry pi 3 using I2c connection... after connection when I check for the device availability using i2cdetect -y 1 command I get an address of 76 in the console for the device but the library takes the default address as 77 how to change the address manually whenever required???.... I'm using this kind of sensor module(image attached below)

![BMP280-Module-Image](https://user-images.githubusercontent.com/32993227/64472534-8987b400-d17d-11e9-99ea-88fe8aa58d22.png)

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_CircuitPython_BMP280/blob/master/adafruit_bmp280.py#L374

**Comment by vasee007** [comment]
its mentioned  "Driver for I2C connected BMP280. Default address is 0x77 but another address can be passed in as an argument"

how to do that??

**Comment by vasee007** [comment]
when I run this code :

import time

import board
# import digitalio # For use with SPI
import busio

import adafruit_bmp280

# Create library object using our Bus I2C port
i2c = busio.I2C(board.SCL, board.SDA)
bmp280 = adafruit_bmp280.Adafruit_BMP280_I2C(i2c)

# OR create library object using our Bus SPI port
#spi = busio.SPI(board.SCK, board.MOSI, board.MISO)
#bmp_cs = digitalio.DigitalInOut(board.D10)
#bmp280 = adafruit_bmp280.Adafruit_BMP280_SPI(spi, bmp_cs)

# change this to match the location's pressure (hPa) at sea level
bmp280.sea_level_pressure = 1013.25

while True:
    print("\nTemperature: %0.1f C" % bmp280.temperature)
    print("Pressure: %0.1f hPa" % bmp280.pressure)
    print("Altitude = %0.2f meters" % bmp280.altitude)
    time.sleep(2)

**Comment by jerryneedell** [comment]
use 
```
bmp280 = adafruit_bmp280.Adafruit_BMP280_I2C(i2c, address = 0x76)
```

**Comment by LuckyLyz** [comment]
> use
> 
> ```
> bmp280 = adafruit_bmp280.Adafruit_BMP280_I2C(i2c, address = 0x76)
> ```
RuntimeError: Failed to find BMP280! Chip ID 0x60

**Comment by jerryneedell** [comment]
Are you using the Adafruit BMP280 Breakout board? If not, what board are you using? The default I2C address is 0x77 or it can be changed to 0x76 if the SDO pin is Grounded.

**Comment by garciajg** [comment]
I'm running into this issue with Raspberry Pi 4
