### ISSUE TITLE
maximum recursion depth exceeded

### ISSUE THREAD

**Issue by hukuzatuna** [adafruit/Adafruit_CircuitPython_BMP280#23]
I am running the BMP280 on a Feather STM32F405 Express running the latest firmware (2020-06-12 downloaded around 0645 Pacific) and library bundle. When I run the example code from the learning guide, it prints the temperature and pressure once, then throws a "maximum recursion depth exceeded" error.
```
Temperature: 21.1 C
Pressure: 1005.7 hPa
Traceback (most recent call last):
  File "code.py", line 25, in <module>
  File "adafruit_bmp280.py", line 358, in altitude
  File "adafruit_bmp280.py", line 328, in pressure
  File "adafruit_bmp280.py", line 149, in _read_temperature
  File "adafruit_bmp280.py", line 214, in mode
  File "adafruit_bmp280.py", line 180, in _write_ctrl_meas
RuntimeError: maximum recursion depth exceeded
```

I'm not sure the proper way to debug this. The code runs fine on the Feather M4 Express. Let me know what I can do to help debug this!

P.S. Here is the code from the learning guide for your convenience:

```import time
 
import board
 
# import digitalio # For use with SPI
import busio
 
import adafruit_bmp280
 
# Create library object using our Bus I2C port
i2c = busio.I2C(board.SCL, board.SDA)
bmp280 = adafruit_bmp280.Adafruit_BMP280_I2C(i2c)
 
# OR create library object using our Bus SPI port
# spi = busio.SPI(board.SCK, board.MOSI, board.MISO)
# bmp_cs = digitalio.DigitalInOut(board.D10)
# bmp280 = adafruit_bmp280.Adafruit_BMP280_SPI(spi, bmp_cs)
 
# change this to match the location's pressure (hPa) at sea level
bmp280.sea_level_pressure = 1013.25
 
while True:
    print("\nTemperature: %0.1f C" % bmp280.temperature)
    print("Pressure: %0.1f hPa" % bmp280.pressure)
    print("Altitude = %0.2f meters" % bmp280.altitude)
    time.sleep(2)
```

**Comment by tannewt** [comment]
I believe this is an issue with the stack size setting on the F405. `maximum recursion depth exceeded` is also means it ran out of stack space. @hierophect would know for sure.

**Comment by hierophect** [comment]
Hmm. I thought I fixed this a while ago. @hukuzatuna, can you post the actual version of Circuitpython you are using as reported by the REPL? Should be the first line that shows up on reset or a manual soft-reboot (ctrl-c, ctrl-d)

**Comment by jerryneedell** [comment]
I was able to run the bmp208_simpletest on v5.4.0-beta

**Comment by hukuzatuna** [comment]
@hierophect It was 5.3.0 build -9285252. 5.4.0 Beta works, by the way, so we can probably close this one.

**Comment by evaherrada** [comment]
Closing
