### ISSUE TITLE
BMP280 SPI Problem

### ISSUE THREAD

**Issue by SalarRah** [adafruit/Adafruit_CircuitPython_BMP280#27]
Happy new year, 

I have tested I2C module and it works great. However, I would like to also set the spi module, which I face a problem receiving proper data. 

the chip Id always changes when using the SPI module for BMP280, and based on my observation, most of the time, it is 0xc0 instead of 0x58 for BMP280. So when I change the id to 0xc0, I am able to connect to the sensor, However, the data is rubbish. I would appreciate it if you help me out in this manner. 

I am using beagle bone green wireless, I have checked my connection multiple times and configured SPI pins correctrly. Thanks in advance.

**Comment by tannewt** [comment]
Hi @SalarRah, for technical support please post on the Adafruit support forum: https://forums.adafruit.com/viewforum.php?f=60
